development:
  access_key_id: "AKIAJI4FS6CKOUH3A7JQ"
  secret_access_key: "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"
  region: "us-west-1"
  simple_db_consistent_reads: false

production:
  access_key_id: "AKIAJI4FS6CKOUH3A7JQ"
  secret_access_key: "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"
  region: "us-west-1"
  simple_db_consistent_reads: true