development:
  access_key_id: ENV["aws_access_key_id"]
  secret_access_key: ENV["aws_secret_access_key"]
  region: 'us-west-1'
production:
  access_key_id: ENV["aws_access_key_id"]
  secret_access_key: ENV["aws_secret_access_key"]
  region: "us-west-1"
